import { createSlice } from "@reduxjs/toolkit";
import { v4 as uuidv4 } from "uuid";

const booksSlice = createSlice({
  name: "books",
  initialState: [
    {
      id: "1",
      title: "To Kill a Mockingbird",
      author: "Harper Lee",
      year: 1960,
      category: "Fiction",
      ISBN: "9780061120084",
      description:
        "A novel about the serious issues of rape and racial inequality.",
      image: "https://covers.openlibrary.org/b/ISBN/9780061120084-L.jpg",
      rating: 4.8,
    },
    {
      id: "2",
      title: "1984",
      author: "George Orwell",
      year: 1949,
      category: "Dystopian",
      ISBN: "9780451524935",
      description:
        "A dystopian novel set in a totalitarian society ruled by Big Brother.",
      image: "https://covers.openlibrary.org/b/ISBN/9780451524935-L.jpg",
      rating: 4.7,
    },
    {
      id: "3",
      title: "Pride and Prejudice",
      author: "Jane Austen",
      year: 1813,
      category: "Romance",
      ISBN: "9781503290563",
      description:
        "A romantic novel that also critiques societal norms of the 19th century.",
      image: "https://covers.openlibrary.org/b/ISBN/9781503290563-L.jpg",
      rating: 4.6,
    },
    {
      id: "4",
      title: "The Great Gatsby",
      author: "F. Scott Fitzgerald",
      year: 1925,
      category: "Fiction",
      ISBN: "9780743273565",
      description:
        "A story of the young and mysterious millionaire Jay Gatsby.",
      image: "https://covers.openlibrary.org/b/ISBN/9780743273565-L.jpg",
      rating: 4.5,
    },
    {
      id: "5",
      title: "War and Peace",
      author: "Leo Tolstoy",
      year: 1869,
      category: "Historical Fiction",
      ISBN: "9781503275928",
      description:
        "A novel about the French invasion of Russia and its impact on society.",
      image: "https://covers.openlibrary.org/b/ISBN/9781503275928-L.jpg",
      rating: 4.3,
    },
    {
      id: "6",
      title: "The Catcher in the Rye",
      author: "J.D. Salinger",
      year: 1951,
      category: "Fiction",
      ISBN: "9780316769488",
      description: "A story about adolescent angst and alienation.",
      image: "https://covers.openlibrary.org/b/ISBN/9780316769488-L.jpg",
      rating: 4.0,
    },
    {
      id: "7",
      title: "The Hobbit",
      author: "J.R.R. Tolkien",
      year: 1937,
      category: "Fantasy",
      ISBN: "9780547928227",
      description: "A fantasy novel following Bilbo Baggins' adventure.",
      image: "https://covers.openlibrary.org/b/ISBN/9780547928227-L.jpg",
      rating: 4.7,
    },
    {
      id: "8",
      title: "Crime and Punishment",
      author: "Fyodor Dostoevsky",
      year: 1866,
      category: "Psychological Fiction",
      ISBN: "9780486415871",
      description: "A novel that explores guilt and redemption.",
      image: "https://covers.openlibrary.org/b/ISBN/9780486415871-L.jpg",
      rating: 4.6,
    },
    {
      id: "9",
      title: "Jane Eyre",
      author: "Charlotte Bronte",
      year: 1847,
      category: "Romance",
      ISBN: "9781503278196",
      description:
        "A love story that also delves into themes of morality and self-respect.",
      image: "https://covers.openlibrary.org/b/ISBN/9781503278196-L.jpg",
      rating: 4.5,
    },
    {
      id: "10",
      title: "The Lord of the Rings",
      author: "J.R.R. Tolkien",
      year: 1954,
      category: "Fantasy",
      ISBN: "9780544003415",
      description: "An epic fantasy journey in the world of Middle-Earth.",
      image: "https://covers.openlibrary.org/b/ISBN/9780544003415-L.jpg",
      rating: 4.8,
    },
    {
      id: "11",
      title: "The Alchemist",
      author: "Paulo Coelho",
      year: 1988,
      category: "Adventure",
      ISBN: "9780061122415",
      description: "A novel about following one’s dreams.",
      image: "https://covers.openlibrary.org/b/ISBN/9780061122415-L.jpg",
      rating: 4.3,
    },
    {
      id: "12",
      title: "Frankenstein",
      author: "Mary Shelley",
      year: 1818,
      category: "Science Fiction",
      ISBN: "9781503262423",
      description: "A Gothic novel about the dangers of playing God.",
      image: "https://covers.openlibrary.org/b/ISBN/9781503262423-L.jpg",
      rating: 4.2,
    },
    {
      id: "13",
      title: "The Odyssey",
      author: "Homer",
      year: "8th century BC",
      category: "Epic Poetry",
      ISBN: "9780140268867",
      description:
        "An epic journey of Odysseus returning home from the Trojan War.",
      image: "https://covers.openlibrary.org/b/ISBN/9780140268867-L.jpg",
      rating: 4.4,
    },
    {
      id: "14",
      title: "The Divine Comedy",
      author: "Dante Alighieri",
      year: 1320,
      category: "Epic Poetry",
      ISBN: "9780140448955",
      description:
        "An allegorical journey through Hell, Purgatory, and Paradise.",
      image: "https://covers.openlibrary.org/b/ISBN/9780140448955-L.jpg",
      rating: 4.5,
    },
    {
      id: "15",
      title: "Hamlet",
      author: "William Shakespeare",
      year: 1603,
      category: "Tragedy",
      ISBN: "9780140714548",
      description: "A tragedy about revenge, madness, and morality.",
      image: "https://covers.openlibrary.org/b/ISBN/9780140714548-L.jpg",
      rating: 4.6,
    },
    {
      id: "16",
      title: "Brave New World",
      author: "Aldous Huxley",
      year: 1932,
      category: "Dystopian",
      ISBN: "9780060850524",
      description: "A dystopian novel set in a futuristic World State society.",
      image: "https://covers.openlibrary.org/b/ISBN/9780060850524-L.jpg",
      rating: 4.3,
    },
    {
      id: "17",
      title: "Les Misérables",
      author: "Victor Hugo",
      year: 1862,
      category: "Historical Fiction",
      ISBN: "9780451419439",
      description:
        "A story of redemption set against the backdrop of revolutionary France.",
      image: "https://covers.openlibrary.org/b/ISBN/9780451419439-L.jpg",
      rating: 4.7,
    },
    {
      id: "18",
      title: "Dracula",
      author: "Bram Stoker",
      year: 1897,
      category: "Horror",
      ISBN: "9780486411095",
      description: "A classic horror novel about the vampire Count Dracula.",
      image: "https://covers.openlibrary.org/b/ISBN/9780486411095-L.jpg",
      rating: 4.4,
    },
  ],
  reducers: {
    addBook(state, action) {
      state.push({ id: uuidv4(), ...action.payload });
    },
  },
});

export const { addBook } = booksSlice.actions;
export default booksSlice.reducer;
